<a href="https://colab.research.google.com/github/sanjeevsbittech/awsartifacts/blob/master/mypoc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import tensorflow as tf
print(tf.version)

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/version/__init__.py'>


In [45]:
str_var = tf.Variable("this is a string",tf.string)
print(str_var)
num_var = tf.Variable(3,tf.int16)
print(num_var)
flt_var = tf.Variable(3.5,tf.float64)
print(flt_var)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.5>


## Concept of Rank
Rank is the dimension of the matrix ie. 1 for dimensional array, 2 for 2 d array

In [46]:
array_str_rank1 = tf.Variable(["hello", "world"], tf.string)
print("string", array_str_rank1)
print("RANK -> rank_one",tf.rank( array_str_rank1))
##rank2
array_str_rank2 = tf.Variable([["hello", "world"],["hello2", "world2"]], tf.string)
print("array_str_rank2 ->", array_str_rank2)
print("RANK -> array_str_rank2 ->",tf.rank( array_str_rank2))

string <tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'hello', b'world'], dtype=object)>
RANK -> rank_one tf.Tensor(1, shape=(), dtype=int32)
array_str_rank2 -> <tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'hello', b'world'],
       [b'hello2', b'world2']], dtype=object)>
RANK -> array_str_rank2 -> tf.Tensor(2, shape=(), dtype=int32)


Concept of Shape
Shape is the number of elements that exist in each dimension e.g. shape of array_str_rank2 in above example is [2,2]

In [47]:
array_str_rank3 = tf.Variable([["hello", "world"],["hello2", "world2"],["hello3", "world3"]], tf.string)
print("array_str_rank3 ->", array_str_rank3)
print("RANK -> array_str_rank3 ->",tf.rank( array_str_rank3))
print("SHAPE OF array_str_rank3 -> ", array_str_rank3.shape)

array_str_rank3 -> <tf.Variable 'Variable:0' shape=(3, 2) dtype=string, numpy=
array([[b'hello', b'world'],
       [b'hello2', b'world2'],
       [b'hello3', b'world3']], dtype=object)>
RANK -> array_str_rank3 -> tf.Tensor(2, shape=(), dtype=int32)
SHAPE OF array_str_rank3 ->  (3, 2)


Concept of reshape

In [53]:
tensor1 = tf.ones([1,2,3])
tensor2 = tf.reshape(tensor1,[2,3,1])
tensor3 = tf.reshape(tensor2, [3, -1])
print(tensor1)
print (tensor2)
print(tensor3)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)
